### ISSUE TITLE
The Group's repo shouldn't be GPL licensed

### ISSUE THREAD

**Issue by ctgraham** [pkp/documentation-interest-group#1]
Commit https://github.com/pkp/documentation-interest-group/commit/438706aa2aebb79a3bfb95f759f7c279d6aba4bb could be construed as applying the GPL v3 license to this repo about the documentation interest group.

This Interest Group repo is probably better suited to apply licenses at the meeting-contribution level, with the internal documentation of the group being licensed under the GNU Free Documentation License or Creative Commons licensing.

**Comment by AhemNason** [comment]
This has since been taken care of.
